### PR TITLE
[BACK-2290] Dexcom patient connection

### PR DESCRIPTION
**Pull request by clintonium-119**
[BACK-2290]

Adds hydrophone client via oapi-codegen in order to be able to get a user's confirmation key and email in the oauth redirect.

[BACK-2290]: https://tidepool.atlassian.net/browse/BACK-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by toddkazakov — CHANGES_REQUESTED** [review]
I believe the client needs its own `go.mod` file, otherwise, importing the package will pull the entire hydrophone repository into vendored dependencies. You can take a look how this is done in the [clinic service](https://github.com/tidepool-org/clinic/blob/master/client/go.mod)

**Comment by toddkazakov** [comment]
The build is also failing and should be fixed

**Review by toddkazakov — APPROVED** [review]

**Comment by clintonium-119** [comment]
@toddkazakov This is ready for an updated review.

I wanted to avoid touching the fragile send signup logic we'd discussed, but didn't want to duplicate the entire code block, so I moved the upsert confirmation portion out to it's own function, unchanged - except in that it returns `nil` or the upserted confirmation - and re-using that bit in a new `POST /confirm/signup/{UserId}` endpoint that is called from clinic-worker prior to sending the dexcom connect email.

Only other significant change was to have `GET /confirm/signup/{UserId}` only return the most recent pending signup confirmation, rather than a list.

The main commit to review is:
https://github.com/tidepool-org/hydrophone/pull/114/commits/b9fb69a4777a83221401f7a414b0aac62ee53bc0

**Review by toddkazakov — DISMISSED** [review]

**Review by toddkazakov — APPROVED** [review]

**Pull request merged**
